name: Reusable Create GitHub Release

on:
  workflow_call:
    inputs:
      tag_name:
        description: 'The tag name for the release'
        required: true
        type: string
      release_name:
        description: 'The name of the release'
        required: true
        type: string
      draft:
        description: 'Whether the release is a draft'
        required: false
        type: boolean
        default: false
      prerelease:
        description: 'Whether the release is a prerelease'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: ${{ inputs.release_name }}
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}