name: Reusable Create GitHub Release

on:
  workflow_call:
    inputs:
      tag:
        description: 'The tag name for the release'
        required: true
        type: string
      name:
        description: 'The name of the release'
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create Release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ inputs.tag }}
          name: ${{ inputs.name }}
          bodyFile: CHANGELOG.md